#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v21
# autospec commit: 8b93847
#
Name     : pypi-safetensors
Version  : 0.5.2
Release  : 10
URL      : https://files.pythonhosted.org/packages/f4/4f/2ef9ef1766f8c194b01b67a63a444d2e557c8fe1d82faf3ebd85f370a917/safetensors-0.5.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/f4/4f/2ef9ef1766f8c194b01b67a63a444d2e557c8fe1d82faf3ebd85f370a917/safetensors-0.5.2.tar.gz
Source1  : http://localhost/cgit/vendor/pypi-safetensors/snapshot/pypi-safetensors-2024-01-30-19-13-59.tar.xz
Source2  : http://localhost/cgit/vendor/pypi-safetensors/snapshot/pypi-safetensors-2025-02-13-23-47-10.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSL-1.0 ICU MIT Unicode-DFS-2016 Unlicense
Requires: pypi-safetensors-license = %{version}-%{release}
Requires: pypi-safetensors-python = %{version}-%{release}
Requires: pypi-safetensors-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(maturin)
BuildRequires : pypi-maturin
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<p align="center">
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://huggingface.co/datasets/safetensors/assets/raw/main/banner-dark.svg">
<source media="(prefers-color-scheme: light)" srcset="https://huggingface.co/datasets/safetensors/assets/raw/main/banner-light.svg">
<img alt="Hugging Face Safetensors Library" src="https://huggingface.co/datasets/safetensors/assets/raw/main/banner-light.svg" style="max-width: 100%;">
</picture>
<br/>
<br/>
</p>

%package license
Summary: license components for the pypi-safetensors package.
Group: Default

%description license
license components for the pypi-safetensors package.


%package python
Summary: python components for the pypi-safetensors package.
Group: Default
Requires: pypi-safetensors-python3 = %{version}-%{release}

%description python
python components for the pypi-safetensors package.


%package python3
Summary: python3 components for the pypi-safetensors package.
Group: Default
Requires: python3-core
Provides: pypi(safetensors)
Provides: pypi(safetensors)

%description python3
python3 components for the pypi-safetensors package.


%prep
%setup -q -n safetensors-0.5.2
cd %{_builddir}
tar xf %{_sourcedir}/pypi-safetensors-2024-01-30-19-13-59.tar.xz
cd %{_builddir}
tar xf %{_sourcedir}/pypi-safetensors-2025-02-13-23-47-10.tar.gz
cd %{_builddir}/safetensors-0.5.2
mkdir -p ./vendor
cp -r %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/. %{_builddir}/safetensors-0.5.2/./vendor
mkdir -p ./vendor
cp -r %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/. %{_builddir}/safetensors-0.5.2/./vendor
mkdir -p .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739490640
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-safetensors
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/memmap2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/c1f96d6a54446beefad79ef49b3c123c597b7a40 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/memmap2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/d5c0c6beed5e77d571189516c53cf05f1e58d9ca || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3-build-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3-build-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3-ffi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3-ffi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3-macros-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3-macros-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3-macros/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3/pyo3-runtime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/pyo3/pyo3-runtime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/pypi-safetensors/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-safetensors/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2024-01-30-19-13-59/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/pypi-safetensors/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/allocator-api2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/96c0ace4eb1b0a78134d978d3c6d656a860a670f || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/bit-set/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/bit-set/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/fcbf534c2fb7782bf6cc7729b11e3cd000e204b2 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/bit-vec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/bit-vec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/fcbf534c2fb7782bf6cc7729b11e3cd000e204b2 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/bumpalo/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/bumpalo/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/0a1e89ac22450cb0311baa2613bc21b7131b321f || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/byteorder/COPYING %{buildroot}/usr/share/package-licenses/pypi-safetensors/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/byteorder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/byteorder/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/cast/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/cast/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/e5c5af8ddef19fbd109a06b28365d6ab491c5a38 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/ciborium-io/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/ciborium-ll/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/ciborium/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/clap_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/clap_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/criterion-plot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/criterion-plot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/b18f451b891c20c5648f7a3034908508f49f015b || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/criterion/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/criterion/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/b18f451b891c20c5648f7a3034908508f49f015b || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/crossbeam-deque/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/crossbeam-deque/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/crossbeam-epoch/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/crossbeam-epoch/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/crunchy/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/ef9d72cbd46e61ffd8d8a6f906ff553eb5f6233c || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/either/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/either/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/equivalent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/equivalent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/c371f0a7cbb203643d88566665a452f96bf1ab86 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/errno/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/errno/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/7a842f34e127456338641b14c7a00ec246d89fb6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/fastrand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/fastrand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/fnv/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/fnv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/getrandom-0.2.15/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/getrandom-0.2.15/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/half/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/b37ac973bb994b8f572a333b2617bddabca57d7d || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/half/LICENSES/Apache-2.0.txt %{buildroot}/usr/share/package-licenses/pypi-safetensors/be561fe6eb626c2566b9a6c0885554b4ee4e6b74 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/half/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/pypi-safetensors/adadb67a9875aeeac285309f1eab6e47d9ee08a7 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/hermit-abi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/hermit-abi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/is-terminal/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/is-terminal/LICENSE-MIT-atty %{buildroot}/usr/share/package-licenses/pypi-safetensors/ffe3aa1f76c00b737c79c3a17b9e30163a936bc0 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/itertools/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/itertools/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/js-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/js-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/linux-raw-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/linux-raw-sys/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-safetensors/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/linux-raw-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/memchr/COPYING %{buildroot}/usr/share/package-licenses/pypi-safetensors/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/memmap2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/c1f96d6a54446beefad79ef49b3c123c597b7a40 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/memmap2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/d5c0c6beed5e77d571189516c53cf05f1e58d9ca || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/once_cell-1.20.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/once_cell-1.20.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/oorandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/83f84f78511c0e3dc95622f9a0b6e151a9ae4ea5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/portable-atomic/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/portable-atomic/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/ppv-lite86/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/088830dcb78eba1a2052df69bd5cba5445e8f2d7 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/ppv-lite86/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/e1c86f32641f01a5b85d6e9b20138e8470b883fc || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/proc-macro2-1.0.92/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/proc-macro2-1.0.92/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/proptest/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/proptest/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/8dc371a451b9630ad353a5801255d8ca5a01d722 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/pyo3-build-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/pyo3-ffi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/pyo3-macros-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/pyo3-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/pyo3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/pyo3/pyo3-runtime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/quick-error/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/quick-error/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/1a00693a4e6240a4d040d1a1f76efaf50f20b8dd || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-safetensors/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-safetensors/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-safetensors/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/0ff30cb09f7056217d089f352fe089b49971eeae || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand_xorshift/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-safetensors/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand_xorshift/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rand_xorshift/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rayon-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rayon-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rayon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rayon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-safetensors/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rustix/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rustix/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-safetensors/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rustix/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rustversion/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rustversion/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rusty-fork/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/rusty-fork/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/8dc371a451b9630ad353a5801255d8ca5a01d722 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/ryu-1.0.18/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/ryu-1.0.18/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/pypi-safetensors/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/pypi-safetensors/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/same-file/COPYING %{buildroot}/usr/share/package-licenses/pypi-safetensors/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/same-file/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/same-file/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/serde_json-1.0.135/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/serde_json-1.0.135/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/syn-2.0.95/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/syn-2.0.95/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/tempfile/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/tempfile/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/70693ba8757c4a17af68e39ab32e4e0d4a389416 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/tinytemplate/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/tinytemplate/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/5875ddc227c505ff2ad6e06538e1d72d403b9060 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/unarray/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/unarray/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/2c87153926f8a458cffc9a435e15571ba721c2fa || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/unicode-ident-1.0.14/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/unicode-ident-1.0.14/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wait-timeout/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wait-timeout/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/walkdir/COPYING %{buildroot}/usr/share/package-licenses/pypi-safetensors/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/walkdir/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/walkdir/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasi-0.11.0+wasi-snapshot-preview1/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasi-0.11.0+wasi-snapshot-preview1/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-safetensors/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasi-0.11.0+wasi-snapshot-preview1/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-safetensors/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasm-bindgen-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasm-bindgen-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasm-bindgen-macro-support/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasm-bindgen-macro-support/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasm-bindgen-macro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasm-bindgen-macro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasm-bindgen-shared/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasm-bindgen-shared/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasm-bindgen/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/wasm-bindgen/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/web-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/web-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/winapi-util/COPYING %{buildroot}/usr/share/package-licenses/pypi-safetensors/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/winapi-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/winapi-util/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/zerocopy-derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/zerocopy-derive/LICENSE-BSD %{buildroot}/usr/share/package-licenses/pypi-safetensors/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/zerocopy-derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/zerocopy/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/zerocopy/LICENSE-BSD %{buildroot}/usr/share/package-licenses/pypi-safetensors/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/zerocopy/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/zerocopy/src/third_party/rust/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2025-02-13-23-47-10/zerocopy/src/third_party/rust/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/safetensors-%{version}/safetensors/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-safetensors/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/pypi-safetensors/088830dcb78eba1a2052df69bd5cba5445e8f2d7
/usr/share/package-licenses/pypi-safetensors/0a1e89ac22450cb0311baa2613bc21b7131b321f
/usr/share/package-licenses/pypi-safetensors/0ff30cb09f7056217d089f352fe089b49971eeae
/usr/share/package-licenses/pypi-safetensors/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/pypi-safetensors/1a00693a4e6240a4d040d1a1f76efaf50f20b8dd
/usr/share/package-licenses/pypi-safetensors/2ad1215c12bd0a3492399dc438aa63084323c662
/usr/share/package-licenses/pypi-safetensors/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/pypi-safetensors/2c87153926f8a458cffc9a435e15571ba721c2fa
/usr/share/package-licenses/pypi-safetensors/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-safetensors/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-safetensors/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/pypi-safetensors/4632a631b427f005d97734ea8c6a44090fec5cd9
/usr/share/package-licenses/pypi-safetensors/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1
/usr/share/package-licenses/pypi-safetensors/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c
/usr/share/package-licenses/pypi-safetensors/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/pypi-safetensors/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/pypi-safetensors/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a
/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-safetensors/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/pypi-safetensors/5875ddc227c505ff2ad6e06538e1d72d403b9060
/usr/share/package-licenses/pypi-safetensors/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/pypi-safetensors/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
/usr/share/package-licenses/pypi-safetensors/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/pypi-safetensors/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/pypi-safetensors/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-safetensors/70693ba8757c4a17af68e39ab32e4e0d4a389416
/usr/share/package-licenses/pypi-safetensors/7a842f34e127456338641b14c7a00ec246d89fb6
/usr/share/package-licenses/pypi-safetensors/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/pypi-safetensors/83f84f78511c0e3dc95622f9a0b6e151a9ae4ea5
/usr/share/package-licenses/pypi-safetensors/8dc371a451b9630ad353a5801255d8ca5a01d722
/usr/share/package-licenses/pypi-safetensors/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/pypi-safetensors/959ce149b1615b8bff3437f59282396756987859
/usr/share/package-licenses/pypi-safetensors/96c0ace4eb1b0a78134d978d3c6d656a860a670f
/usr/share/package-licenses/pypi-safetensors/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/pypi-safetensors/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/pypi-safetensors/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/pypi-safetensors/adadb67a9875aeeac285309f1eab6e47d9ee08a7
/usr/share/package-licenses/pypi-safetensors/b18f451b891c20c5648f7a3034908508f49f015b
/usr/share/package-licenses/pypi-safetensors/b37ac973bb994b8f572a333b2617bddabca57d7d
/usr/share/package-licenses/pypi-safetensors/be561fe6eb626c2566b9a6c0885554b4ee4e6b74
/usr/share/package-licenses/pypi-safetensors/c1f96d6a54446beefad79ef49b3c123c597b7a40
/usr/share/package-licenses/pypi-safetensors/c371f0a7cbb203643d88566665a452f96bf1ab86
/usr/share/package-licenses/pypi-safetensors/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/pypi-safetensors/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/pypi-safetensors/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-safetensors/d5c0c6beed5e77d571189516c53cf05f1e58d9ca
/usr/share/package-licenses/pypi-safetensors/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/pypi-safetensors/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/pypi-safetensors/e1c86f32641f01a5b85d6e9b20138e8470b883fc
/usr/share/package-licenses/pypi-safetensors/e5c5af8ddef19fbd109a06b28365d6ab491c5a38
/usr/share/package-licenses/pypi-safetensors/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/pypi-safetensors/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/pypi-safetensors/ebbc0758a0322f1bfe28f5438867a084e53941c8
/usr/share/package-licenses/pypi-safetensors/ef9d72cbd46e61ffd8d8a6f906ff553eb5f6233c
/usr/share/package-licenses/pypi-safetensors/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-safetensors/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/pypi-safetensors/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/pypi-safetensors/f911b0506e6ba6a56b4edac717b461799f380ef0
/usr/share/package-licenses/pypi-safetensors/fcbf534c2fb7782bf6cc7729b11e3cd000e204b2
/usr/share/package-licenses/pypi-safetensors/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
/usr/share/package-licenses/pypi-safetensors/ffe3aa1f76c00b737c79c3a17b9e30163a936bc0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
