#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cargo
#
Name     : pypi-safetensors
Version  : 0.3.3
Release  : 5
URL      : https://files.pythonhosted.org/packages/ea/43/9911dc3ab9c8da3ef0ecf9c81cca132327f73beb22be9b03eaa9f3070d40/safetensors-0.3.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/ea/43/9911dc3ab9c8da3ef0ecf9c81cca132327f73beb22be9b03eaa9f3070d40/safetensors-0.3.3.tar.gz
Source1  : http://localhost/cgit/vendor/pypi-safetensors/snapshot/pypi-safetensors-2023-07-28-20-05-43.tar.xz
Summary  : Fast and Safe Tensor serialization
Group    : Development/Tools
License  : Apache-2.0 BSL-1.0 MIT Unicode-DFS-2016
Requires: pypi-safetensors-license = %{version}-%{release}
Requires: pypi-safetensors-python = %{version}-%{release}
Requires: pypi-safetensors-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools_rust)
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
## Installation
```
pip install safetensors
```
## Usage
### Numpy
```python
from safetensors.numpy import save_file, load_file
import numpy as np

%package license
Summary: license components for the pypi-safetensors package.
Group: Default

%description license
license components for the pypi-safetensors package.


%package python
Summary: python components for the pypi-safetensors package.
Group: Default
Requires: pypi-safetensors-python3 = %{version}-%{release}

%description python
python components for the pypi-safetensors package.


%package python3
Summary: python3 components for the pypi-safetensors package.
Group: Default
Requires: python3-core
Provides: pypi(safetensors)

%description python3
python3 components for the pypi-safetensors package.


%prep
%setup -q -n safetensors-0.3.3
cd %{_builddir}
tar xf %{_sourcedir}/pypi-safetensors-2023-07-28-20-05-43.tar.xz
cd %{_builddir}/safetensors-0.3.3
mkdir -p ./vendor
cp -r %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/* %{_builddir}/safetensors-0.3.3/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-safetensors
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/memmap2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/c1f96d6a54446beefad79ef49b3c123c597b7a40 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/memmap2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/d5c0c6beed5e77d571189516c53cf05f1e58d9ca || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/pyo3-build-config/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/pyo3-macros-backend/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/pyo3-macros/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/pyo3/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/pypi-safetensors/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/syn-1.0.109/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/syn-1.0.109/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-safetensors/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-safetensors/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-safetensors-2023-07-28-20-05-43/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-safetensors/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/pypi-safetensors/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-safetensors/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-safetensors/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/pypi-safetensors/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-safetensors/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/pypi-safetensors/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/pypi-safetensors/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/pypi-safetensors/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-safetensors/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/pypi-safetensors/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/pypi-safetensors/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/pypi-safetensors/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/pypi-safetensors/c1f96d6a54446beefad79ef49b3c123c597b7a40
/usr/share/package-licenses/pypi-safetensors/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/pypi-safetensors/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-safetensors/d5c0c6beed5e77d571189516c53cf05f1e58d9ca
/usr/share/package-licenses/pypi-safetensors/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/pypi-safetensors/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-safetensors/f498d95a48889a0b1432e420e6754881eff1d593

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
